#!/usr/bin/env bash
set -e
out=pybest/data/ni-edu.tar.gz
if [ -f $out ]; then
    echo "Data is already downloaded!"
    if [ -d pybest/data/ni-edu ]; then
	exit 0
    fi
else
    echo "Downloading data ..."
    curl -o pybest/data/ni-edu.tar.gz https://surfdrive.surf.nl/files/index.php/s/f9oBCx8tswGgojx/download
fi
echo "Unzipping data ..."
tar -xzvf pybest/data/ni-edu.tar.gz -C pybest/data
rm pybest/data/ni-edu.tar.gz